# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-04-03 22:43
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('business', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=500)),
                ('job_function', models.CharField(max_length=100)),
                ('employment_type', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=500)),
                ('skills', models.CharField(max_length=100)),
                ('qualifications', models.CharField(max_length=100)),
                ('instructions', models.CharField(max_length=100)),
                ('poc', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=100, validators=[django.core.validators.EmailValidator()])),
                ('phone', models.CharField(blank=True, max_length=20, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '999-999-9999'.", regex='^\\d{3}--\\d{3}--\\d{4}$')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Jobs', to='business.Business')),
            ],
        ),
    ]
