# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-07-14 17:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_auto_20180713_1633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='job_function',
            field=models.CharField(max_length=100),
        ),
    ]
