# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-04-03 22:43
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import localflavor.us.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('industry', models.CharField(choices=[('72', 'Accommodation and food services'), ('56', 'Administrative and waste services'), ('11', 'Agriculture, forestry, fishing and hunting'), ('71', 'Arts, entertainment, and recreation'), ('23', 'Construction'), ('61', 'Educational services'), ('52', 'Finance and insurance'), ('62', 'Health care and social assistance'), ('51', 'Information'), ('55', 'Management of companies and enterprises'), ('31', 'Manufacturing'), ('32', 'Manufacturing'), ('21', 'Mining, quarrying, and oil and gas extraction'), ('81', 'Other services, except public administration'), ('54', 'Professional and technical services'), ('92', 'Public administration'), ('53', 'Real estate and rental and leasing'), ('44', 'Retail trade'), ('48', 'Transportation and warehousing'), ('99', 'Unclassified'), ('22', 'Utilities'), ('42', 'Wholesale trade')], default='', max_length=2, validators=[django.core.validators.RegexValidator(message='Please select an industry from the list.', regex='^[0-9]{2}$')])),
                ('subindustry', models.CharField(blank=True, choices=[('721', 'Accommodation'), ('722', 'Food services and drinking places')], default='', max_length=3)),
                ('website', models.CharField(blank=True, max_length=100, validators=[django.core.validators.URLValidator()])),
                ('email', models.EmailField(blank=True, max_length=100, validators=[django.core.validators.EmailValidator()])),
                ('phone', models.CharField(blank=True, max_length=20, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '999-999-9999'.", regex='^\\d{3}-\\d{3}-\\d{4}(\\sext.\\d{1,5})?$')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Primary', max_length=50)),
                ('is_primary', models.BooleanField(default=True)),
                ('street', models.CharField(default='', max_length=50)),
                ('city', models.CharField(default='', max_length=50)),
                ('state', models.CharField(choices=[(b'AK', 'Alaska'), (b'AL', 'Alabama'), (b'AR', 'Arkansas'), (b'AZ', 'Arizona'), (b'CA', 'California'), (b'CO', 'Colorado'), (b'CT', 'Connecticut'), (b'DC', 'District of Columbia'), (b'DE', 'Delaware'), (b'FL', 'Florida'), (b'GA', 'Georgia'), (b'HI', 'Hawaii'), (b'IA', 'Iowa'), (b'ID', 'Idaho'), (b'IL', 'Illinois'), (b'IN', 'Indiana'), (b'KS', 'Kansas'), (b'KY', 'Kentucky'), (b'LA', 'Louisiana'), (b'MA', 'Massachusetts'), (b'MD', 'Maryland'), (b'ME', 'Maine'), (b'MI', 'Michigan'), (b'MN', 'Minnesota'), (b'MO', 'Missouri'), (b'MS', 'Mississippi'), (b'MT', 'Montana'), (b'NC', 'North Carolina'), (b'ND', 'North Dakota'), (b'NE', 'Nebraska'), (b'NH', 'New Hampshire'), (b'NJ', 'New Jersey'), (b'NM', 'New Mexico'), (b'NV', 'Nevada'), (b'NY', 'New York'), (b'OH', 'Ohio'), (b'OK', 'Oklahoma'), (b'OR', 'Oregon'), (b'PA', 'Pennsylvania'), (b'RI', 'Rhode Island'), (b'SC', 'South Carolina'), (b'SD', 'South Dakota'), (b'TN', 'Tennessee'), (b'TX', 'Texas'), (b'UT', 'Utah'), (b'VA', 'Virginia'), (b'VT', 'Vermont'), (b'WA', 'Washington'), (b'WI', 'Wisconsin'), (b'WV', 'West Virginia'), (b'WY', 'Wyoming')], default='IL', max_length=2)),
                ('zipcode', localflavor.us.models.USZipCodeField(max_length=10)),
                ('phone', models.CharField(blank=True, max_length=20, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '999-999-9999'.", regex='^\\d{3}-\\d{3}-\\d{4}(\\sext.\\d{1,5})?$')])),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='business.Business')),
            ],
        ),
    ]
