# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-04-14 22:39
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('business', '0002_auto_20180407_1410'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='created_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='businesses_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='business',
            name='poc_role',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='business',
            name='primary_poc',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
