# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-04-14 22:48
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0003_auto_20180414_1739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='businesses_created', to=settings.AUTH_USER_MODEL),
        ),
    ]
