# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-04-14 23:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0004_auto_20180414_1748'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='status',
            field=models.CharField(choices=[('submitted', 'Submitted'), ('review', 'Under Review'), ('approved', 'Approved')], default='submitted', max_length=10),
        ),
    ]
