# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-05-21 14:31
from __future__ import unicode_literals

from django.db import migrations, models
import localflavor.us.models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0005_business_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='street',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='zipcode',
            field=localflavor.us.models.USZipCodeField(blank=True, max_length=10),
        ),
    ]
